title: VRChat API Documentation
email: me@ruby.js.org
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://vrchatapi.github.io"

markdown: kramdown
highlighter: rouge

# https://stackoverflow.com/a/17913214/2479087
tutorial-categories:
  - id: general
    name: General
  - id: node
    name: Node SDK
#  - id: python
#    name: Python SDK
  - id: java
    name: Java SDK
  - id: dart
    name: Dart SDK
  - id: rust
    name: Rust SDK
  - id: csharp
    name: C# SDK

sdks:
  - id: node
    name: Node
    repo: vrchatapi-javascript
    description: NodeJS is a JavaScript runtime allowing you to write JavaScript or TypeScript on the backend.
#  - id: python
#    name: Python
#    repo: vrchatapi-python
#    description: Python is an easy to learn scripting language for developing terminal or backend applications.
  - id: java
    name: Java
    repo: vrchatapi-java
    description: Java is a high-level, class-based OOP language for both desktop, backend and Android.
  - id: dart
    name: Dart
    repo: vrchatapi-dart
    description: Dart is a client-side language allowing compilation for both Android, iOS, web, and terminal.
  - id: rust
    name: Rust
    repo: vrchatapi-rust
    description: Rust is a fast and secure language with no runtime nor garbace-collector, whos memory-management makes memory bugs impossible.
  - id: csharp
    name: C#
    repo: vrchatapi-csharp
    description: C# is a high-level, class-based OOP langauge, part of .NET, and builds for desktop and Unity.
